### ISSUE TITLE
Cut first release and post example to bl.ocks.org

### ISSUE THREAD

**Issue by curran** [chiasm-project/chiasm-charts#15]
* [X] add npm script that produces a UMD module for use on bl.ocks.org
 * [X] Cut first release
 * [X] put UMD bundle on gh-pages as CDN
 * [X] post example to bl.ocks.org
 * [X] add example link with thumbnail to README
 * [ ] Update example to use CDN ref
  * [X] Update chiasm-dataset-loader https://github.com/chiasm-project/chiasm-dataset-loader/issues/3
  * [X] Update chiasm-component https://github.com/chiasm-project/chiasm-component/issues/2
  * [ ] Update chiasm-links https://github.com/chiasm-project/chiasm-links/issues/2

**Comment by curran** [comment]
This first release will follow the practice of shimming D3 and other modules out of the bundle.

**Comment by curran** [comment]
Made partial progress on working browser build version:

```
<!-- Load shared dependencies. -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

<!-- Load the Chiasm stack. -->
<script src="http://chiasm-project.github.io/chiasm/chiasm-v0.3.0.min.js"></script>
<script src="http://curran.github.io/model/cdn/model-v0.2.4.js"></script>
<script src="http://chiasm-project.github.io/chiasm-component/chiasm-component-v0.2.0.js"></script>
<script src="http://chiasm-project.github.io/chiasm-layout/chiasm-layout-v0.2.1.js"></script>
<script src="http://chiasm-project.github.io/chiasm-dataset-loader/chiasm-dataset-loader-v0.3.1.js"></script>
<script src="http://chiasm-project.github.io/chiasm-data-reduction/chiasm-data-reduction-v0.3.0.js"></script>
<script src="http://chiasm-project.github.io/chiasm-links/chiasm-links-v0.2.1.js"></script>
<script src="http://chiasm-project.github.io/chiasm-charts/chiasm-charts-v0.1.0.js"></script>
```
This would have much fewer script tags if Chiasm had a default build with all these modules in it https://github.com/chiasm-project/chiasm/issues/57 .

**Comment by curran** [comment]
This is the example http://bl.ocks.org/curran/46050d18d5ec1ab401fa
